### ISSUE TITLE
big training error with mse loss

### ISSUE THREAD

**Issue by McDo** [3ammor/Variational-Autoencoder-in-pytorch#1]
Hello,
Thanks for your great code. 
Here I've got a big training error with the mean squared loss ( ~2470 and wouldn't be going down further ). 
Does it mean that here is a high bias problem with the model, and the encoder and decoder should be going more deeper?

**Comment by o-tawab** [comment]
Hi,

I trained this model on CIFAR10 with both losses(MSE and CE), and what I observed is that MSE loss doesn't work with the VAE (or at least it didn't in my case).

What I tried is converting the problem to classification instead of regression (where I would predict the class of each pixel from 256 classes), and that way I can apply corss-entropy loss. The output from training with the CE loss turned out to be much better than the MSE loss.

**Comment by McDo** [comment]
thank you, gonna give it a try.
